---
Bot:
    CommandPrefix: '?'
    Activity: '?help for help'
    CogDirectory: cogs
    Cogs:
        - anagrams
        - garlic

Anagram:
    Corpus: resources/anagrams/words.json
    NoOfQuestions: 10
    QuestionLimit: 50
    TimeToFirstQuestion: 3
    TimeToNextQuestion: 6
    TimePerQuestion: 30
    TimeToFirstHint: 10
    TimeToSecondHint: 5
    TimeToSecondHintShortWords: 13
    ShortWordLengthCutoff: 7

Garlic:
    Template: resources/garlic/Template.jpeg
    DarkTemplate: resources/garlic/DarkTemplate.png
    Font: resources/garlic/CooperHewitt-Heavy.otf